/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.godardstudios.gui;

import com.godardstudios.tool.IconsImg;
import java.util.ResourceBundle;

import javax.swing.Icon;
//import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author cflor
 */
public class PanelPrincipal extends javax.swing.JPanel {

    ListaTarea TareasList = new ListaTarea();
    ResourceBundle lenguage ;
    // ArrayList<JCheckbox> jboxTareas = new ArrayList<>();

    /**
     * Creates new form PanelPrincipal
     * @param lenguaje
     */
    public PanelPrincipal(ResourceBundle  lenguaje) {
        this.lenguage = lenguaje;
        initComponents();
        

    }

    public void repintarTareas(boolean bandera) {
        if (bandera) {
            panelTareas.removeAll();
            for (JCheckbox jboxTarea : TareasList.getJboxTareas()) {
                panelTareas.add(jboxTarea);
            }
            panelTareas.updateUI();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHerramientas = new javax.swing.JPanel();
        btnAgregarTarea = new javax.swing.JButton();
        btnElimiarTareasConcluidas = new javax.swing.JButton();
        btnEliminarTareasPendientes = new javax.swing.JButton();
        btnTareas = new javax.swing.JButton();
        jPanelEspacio = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        panelTareas = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        PanelHerramientas.setLayout(new javax.swing.BoxLayout(PanelHerramientas, javax.swing.BoxLayout.Y_AXIS));

        btnAgregarTarea.setText(lenguage.getString("PanelPrincipal.btnAgregarTarea.text")); // NOI18N
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });
        PanelHerramientas.add(btnAgregarTarea);
        btnAgregarTarea.getAccessibleContext().setAccessibleDescription(lenguage.getString("PanelPrincipal.btnAgregarTarea.AccessibleContext.accessibleDescription")); // NOI18N

        btnElimiarTareasConcluidas.setText(lenguage.getString("PanelPrincipal.btnElimiarTareasConcluidas.text")); // NOI18N
        btnElimiarTareasConcluidas.setToolTipText(lenguage.getString("PanelPrincipal.btnElimiarTareasConcluidas.toolTipText")); // NOI18N
        btnElimiarTareasConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiarTareasConcluidasActionPerformed(evt);
            }
        });
        PanelHerramientas.add(btnElimiarTareasConcluidas);

        btnEliminarTareasPendientes.setText(lenguage.getString("btnEliminarTareasPendientes.setText"));
        btnEliminarTareasPendientes.setToolTipText(lenguage.getString("PanelPrincipal.btnEliminarTareasPendientes.toolTipText")); // NOI18N
        btnEliminarTareasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareasPendientesActionPerformed(evt);
            }
        });
        PanelHerramientas.add(btnEliminarTareasPendientes);

        btnTareas.setText(lenguage.getString("PanelPrincipal.btnTareas.text")); // NOI18N
        btnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareasActionPerformed(evt);
            }
        });
        PanelHerramientas.add(btnTareas);

        jPanelEspacio.setLayout(new java.awt.BorderLayout());
        PanelHerramientas.add(jPanelEspacio);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Studios.png"))); // NOI18N
        lblLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoMouseExited(evt);
            }
        });
        PanelHerramientas.add(lblLogo);

        add(PanelHerramientas, java.awt.BorderLayout.LINE_START);

        ScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, lenguage.getString("PanelPrincipal.ScrollPane.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N

        panelTareas.setLayout(new javax.swing.BoxLayout(panelTareas, javax.swing.BoxLayout.Y_AXIS));
        ScrollPane.setViewportView(panelTareas);

        add(ScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        Icon nm = new IconsImg("/iconsAñadirEtiqueta.png").getIcon();
        String msj = (String) JOptionPane.showInputDialog(
                this,
                lenguage.getString("JOptionPane.showInputDialog.NameTarea"), lenguage.getString("JOptionPane.showInputDialog.Ingresar"),
                JOptionPane.DEFAULT_OPTION, nm, null, "");

        if (msj != null && !msj.equals("")) {

            JCheckbox tarea = TareasList.agregarTarea(msj);
//            JCheckbox tarea = new JCheckbox(msj, false);
//            tarea.setFont(new Font("Tahoma", Font.PLAIN, 16));
//            jboxTareas.add(tarea);
            panelTareas.add(tarea);
            panelTareas.updateUI();
        }

    }//GEN-LAST:event_btnAgregarTareaActionPerformed

    private void btnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareasActionPerformed
        // TODO add your handling code here:
        TareasList.infListTareas();

    }//GEN-LAST:event_btnTareasActionPerformed

    private void btnElimiarTareasConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiarTareasConcluidasActionPerformed
        // TODO add your handling code here:
        if (!TareasList.getJboxTareas().isEmpty() && TareasList.hayTareasConcluidas()) {
            String msj = lenguage.getString("JOptionPane.showOptionDialog.msj");
            Object[] opciones = {lenguage.getString("JOptionPane.showOptionDialog.aceptar"), lenguage.getString("JOptionPane.showOptionDialog.cancelar")};
            int eleccion = JOptionPane.showOptionDialog(this, msj, lenguage.getString("JOptionPane.showOptionDialog.msjConfir"),
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, new IconsImg("/icons-eliminar.png").getIcon(), opciones, lenguage.getString("JOptionPane.showOptionDialog.aceptar"));
            if (eleccion == JOptionPane.YES_OPTION) {
                boolean bandera = TareasList.eliminarTareasConcluidas();
                repintarTareas(bandera);
            }
        } else {
            JOptionPane.showMessageDialog(this, lenguage.getString("JOptionPane.showMessageDialog.NohayTareas"), lenguage.getString("JOptionPane.showOptionDialog.msj2"), JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_btnElimiarTareasConcluidasActionPerformed

    private void btnEliminarTareasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareasPendientesActionPerformed
        // TODO add your handling code here:
        if (!TareasList.getJboxTareas().isEmpty()) {
            panelTareas.removeAll();
            TareasList.getJboxTareas().clear();
            panelTareas.updateUI();
            JOptionPane.showMessageDialog(this, lenguage.getString("JOptionPane.showMessageDialog.TarElim"), lenguage.getString("logro"), JOptionPane.INFORMATION_MESSAGE, new IconsImg("/icons-ok.png").getIcon());
        } else {
            JOptionPane.showMessageDialog(this, lenguage.getString("Mensj.NohayTareas"), lenguage.getString("JOptionPane.showOptionDialog.msj2"), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarTareasPendientesActionPerformed

    private void lblLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseEntered
        // TODO add your handling code here:
        try {
            lblLogo.setIcon(new IconsImg("/studio_pop.png").getIcon());
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_lblLogoMouseEntered

    private void lblLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseExited
        // TODO add your handling code here:
        try {
            lblLogo.setIcon(new IconsImg("/Studios.png").getIcon());
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_lblLogoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHerramientas;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnElimiarTareasConcluidas;
    private javax.swing.JButton btnEliminarTareasPendientes;
    private javax.swing.JButton btnTareas;
    private javax.swing.JPanel jPanelEspacio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panelTareas;
    // End of variables declaration//GEN-END:variables
}
